#!/usr/bin/env python3
"""Generate the complete dissertation figure set from one command.

Non-spatial figures are generated by default.  Maps are opt-in because their
external OSM and MATSim inputs are not part of the analysis-results archive.
"""

from __future__ import annotations

import argparse
from pathlib import Path
import subprocess
import sys


HERE = Path(__file__).resolve().parent


def run(script: Path, arguments: list[str]) -> None:
    command = [sys.executable, str(script), *arguments]
    print("\n$", " ".join(command), flush=True)
    subprocess.run(command, check=True, cwd=HERE)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--analysis-source",
        type=Path,
        required=True,
        help="Extracted analysis_results directory or ABC analysis tar.gz",
    )
    parser.add_argument(
        "--output-dir", type=Path, default=Path("figures"), help="PNG output directory"
    )
    parser.add_argument(
        "--include-maps",
        action="store_true",
        help="Also generate Figures 3.1, B.5 and B.10",
    )
    parser.add_argument("--spatial-context", type=Path)
    parser.add_argument("--osm-dir", type=Path)
    parser.add_argument("--berlin-boundary", type=Path)
    parser.add_argument("--transit-schedule", type=Path)
    parser.add_argument("--network", type=Path)
    parser.add_argument(
        "--map-dpi", type=int, default=300,
        help="Resolution for the optional map exports (default: 300)",
    )
    parser.add_argument(
        "--no-strict-maps",
        action="store_true",
        help="Warn instead of failing if mapped sample sizes differ from frozen QA values",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    analysis = str(args.analysis_source.resolve())
    output = str(args.output_dir.resolve())
    common = ["--analysis-source", analysis, "--output-dir", output, "--figures", "all"]
    run(HERE / "make_main_figures.py", common)
    run(HERE / "make_appendix_figures.py", common)

    if not args.include_maps:
        print(
            "\nGenerated every non-spatial figure. Maps 3.1, B.5 and B.10 were "
            "skipped; pass --include-maps with the documented external inputs."
        )
        return

    required = {
        "--spatial-context": args.spatial_context,
        "--osm-dir": args.osm_dir,
        "--berlin-boundary": args.berlin_boundary,
        "--transit-schedule": args.transit_schedule,
        "--network": args.network,
    }
    missing = [name for name, value in required.items() if value is None]
    if missing:
        raise SystemExit("Map generation requires: " + ", ".join(missing))

    map_common = [
        "--spatial-context",
        str(args.spatial_context.resolve()),
        "--osm-dir",
        str(args.osm_dir.resolve()),
        "--transit-schedule",
        str(args.transit_schedule.resolve()),
        "--network",
        str(args.network.resolve()),
        "--dpi",
        str(args.map_dpi),
    ]
    run(
        HERE / "maps" / "make_figure_3_1.py",
        [
            *map_common,
            "--berlin-boundary",
            str(args.berlin_boundary.resolve()),
            "--output",
            str((args.output_dir / "Figure_3_1_Berlin_DRT_cases.png").resolve()),
        ],
    )
    strict_flag = ["--no-strict"] if args.no_strict_maps else []
    for script, filename in (
        ("make_figure_B5.py", "Figure_B5_residential_cell_utility_map.png"),
        ("make_figure_B10.py", "Figure_B10_residential_cell_utility_case_C.png"),
    ):
        run(
            HERE / "maps" / script,
            [
                "--analysis-source",
                analysis,
                *map_common,
                "--output",
                str((args.output_dir / filename).resolve()),
                *strict_flag,
            ],
        )


if __name__ == "__main__":
    main()
